/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type { Score2048, Score2048Interface } from "../Score2048";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "player",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "score",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "newBest",
        type: "uint32",
      },
    ],
    name: "ScoreSubmitted",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "best",
    outputs: [
      {
        internalType: "uint32",
        name: "",
        type: "uint32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint32",
        name: "score",
        type: "uint32",
      },
    ],
    name: "submitScore",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5061039a806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c8063038cfeb71461003b578063d53bb09214610057575b600080fd5b61005560048036038101906100509190610259565b610087565b005b610071600480360381019061006c91906102e4565b6101f5565b60405161007e9190610320565b60405180910390f35b60008060003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060009054906101000a900463ffffffff1690508063ffffffff168263ffffffff1611156101a057816000803373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060006101000a81548163ffffffff021916908363ffffffff1602179055503373ffffffffffffffffffffffffffffffffffffffff167f20524a37dabae5d06ccca10586e8d42fa205c69d14f6513311658f0d30d9ada3838460405161019392919061033b565b60405180910390a26101f1565b3373ffffffffffffffffffffffffffffffffffffffff167f20524a37dabae5d06ccca10586e8d42fa205c69d14f6513311658f0d30d9ada383836040516101e892919061033b565b60405180910390a25b5050565b60006020528060005260406000206000915054906101000a900463ffffffff1681565b600080fd5b600063ffffffff82169050919050565b6102368161021d565b811461024157600080fd5b50565b6000813590506102538161022d565b92915050565b60006020828403121561026f5761026e610218565b5b600061027d84828501610244565b91505092915050565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b60006102b182610286565b9050919050565b6102c1816102a6565b81146102cc57600080fd5b50565b6000813590506102de816102b8565b92915050565b6000602082840312156102fa576102f9610218565b5b6000610308848285016102cf565b91505092915050565b61031a8161021d565b82525050565b60006020820190506103356000830184610311565b92915050565b60006040820190506103506000830185610311565b61035d6020830184610311565b939250505056fea26469706673582212201da9276aabaab06bb7258d71e107a62b5677b12ae906f01efe6c5d21cb2fd7cc64736f6c63430008180033";

type Score2048ConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: Score2048ConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Score2048__factory extends ContractFactory {
  constructor(...args: Score2048ConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Score2048 & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Score2048__factory {
    return super.connect(runner) as Score2048__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): Score2048Interface {
    return new Interface(_abi) as Score2048Interface;
  }
  static connect(address: string, runner?: ContractRunner | null): Score2048 {
    return new Contract(address, _abi, runner) as unknown as Score2048;
  }
}
