/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Score2048 } from "./Score2048";
export * as factories from "./factories";
export { Score2048__factory } from "./factories/Score2048__factory";
